---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: З днем народження
description: В ході цього проекту ви ознайомитесь з HTML та CSS, практикуючись у створенні власної вітальної листівки.
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: З днем народження
  - 
    title: Що вам знадобиться
  - 
    title: Що таке HTML?
  - 
    title: 'Завдання: додати ще один абзац'
  - 
    title: Що таке CSS?
  - 
    title: 'Завдання: додати більше стилів'
  - 
    title: Створення листівки
  - 
    title: 'Завдання: створити свою листівку'
