---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Gefeliciteerd
description: Maak een online verjaardagskaart op een webpagina
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: 'kunst en ontwerp'
technologies: html/css
site_areas: codeclub, webdev
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: What is HTML?
  - 
    title: 'Challenge: add another paragraph'
  - 
    title: What is CSS?
  - 
    title: 'Challenge: add more styles'
  - 
    title: Making a birthday card
  - 
    title: 'Challenge: create a personalised card'
