---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Gefeliciteerd
description: Maak een online verjaardagskaart op een webpagina
original_url: https://codeclubprojects.org/nl-NL/webdev/happy-birthday
interests: kunst
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
- title: Inleiding
- title: Wat heb je nodig
  completion: engaged
- title: Wat is HTML?
- title: 'Uitdaging: voeg een nieuwe alinea toe'
- title: Wat is CSS?
- title: 'Uitdaging: voeg meer stijlen toe'
- title: Een verjaardagskaart maken
  completion: internal
- title: 'Uitdaging: een persoonlijke kaart maken'
