---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: वाढदिवसाच्या हार्दिक शुभेच्छा
description: Webpage वर वाढदिवसाचे ऑनलाईन शुभेच्छापत्र बनवा
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
- title: परिचय
- title: आपल्याला कशाची गरज असेल
- title: HTML म्हणजे काय?
- title: 'आव्हान: अजून एक परिच्छेद जोडा'
- title: CSS म्हणजे काय?
  completion:
  - engaged
- title: 'आव्हान: अजून स्टाईलची भर घाला'
- title: वाढदिवसाचे शुभेच्छापत्र बनवणे
  completion:
  - internal
- title: 'आव्हान: वैयक्तिकृत शुभेच्छापत्र बनवा'
