---
hero_image: images/happy-birthday.png
theme: फ़िरोज़ी
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: जन्मदिन की बधाई
description: जन्मदिन का कस्टमाइज़्ड कार्ड बनाना सीखें
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art and design
technologies: html/css
site_areas: प्रोजेक्ट
hardware: ''
software: html/css
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: आपको किन चीजों की आवश्यकता होगी
  - 
    title: HTML क्या है?
  - 
    title: 'चुनौती: एक और अनुच्छेद जोड़ें'
  - 
    title: CSS क्या है?
  - 
    title: 'चुनौती: और स्टाइल जोड़ें'
  - 
    title: जन्मदिन कार्ड बनाना
  - 
    title: 'चुनौती: निजीकृत कार्ड बनाएँ'
