---
hero_image: images/happy-birthday.png
theme: тиркиз
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, дизајн-1, програмирање-0, физ-комп-0, производња-0, заједница-0
title: Срећан рођендан
description: Направи онлајн честитку за рођендан на интернет страници
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: уметност
technologies: html-css-javascript
site_areas: пројекти
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Увод
  - 
    title: Шта ће ти требати
  - 
    title: Шта је HTML?
  - 
    title: 'Challenge: додај још један пасус'
  - 
    title: Шта је CSS?
  - 
    title: 'Challenge: додај још стилова'
  - 
    title: Прављење честитке за рођендан
  - 
    title: 'Challenge: направи персонализовану честитку'
