---
hero_image: bilder / happy-birthday.png
theme: turkis
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programmering-0, phys-comp-0, produksjon-0, fellesskap-0
title: Gratulerer med dagen
description: Lag et online bursdagskort på en nettside
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: Kunst
technologies: html-css-javascript
site_areas: prosjekter
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduksjon
  - 
    title: Hva du trenger
  - 
    title: Hva er HTML?
  - 
    title: 'Utfordring: Legg til et annet avsnitt'
  - 
    title: Hva er CSS?
  - 
    title: 'Utfordring: Legg til flere stiler'
  - 
    title: Gjør et bursdagskort
  - 
    title: 'Utfordring: Lag et personlig kort'
