---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Happy birthday
description: Make an online birthday card on a webpage
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: పరిచయం లేదా ఇంట్రొడక్షన్
  - 
    title: మీకు అవసరమైన విషయాలు
  - 
    title: HTML అంటే ఏమిటి?
  - 
    title: 'ఛాలెంజ్: మరొక పేరాను జోడించండి'
  - 
    title: CSS అంటే ఏమిటి?
  - 
    title: 'ఛాలెంజ్: మరికొన్ని స్టైల్లు జోడించండి'
  - 
    title: పుట్టినరోజు కార్డు తయారు విధానం
  - 
    title: 'Challenge: create a personalised card'
