---
hero_image: images/happy-birthday.png
theme: màu ngọc lam
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, thiết kế-1, lập trình-0, Phys-comp-0, sản xuất-0, cộng đồng-0
title: Chúc mừng sinh nhật
description: Làm thiệp sinh nhật trực tuyến trên một trang web
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: nghệ thuật
technologies: html-css-javascript
site_areas: dự án
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: HTML là gì?
  - 
    title: 'Thử thách: thêm một đoạn khác'
  - 
    title: CSS là gì?
  - 
    title: 'Thử thách: thêm phong cách khác'
  - 
    title: Làm thiệp sinh nhật
  - 
    title: 'Thử thách: tạo một thiệp cá nhân'
