---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tillykke Med Fødselsdagen
description: I dette projekt bliver du introduceret til HTML & CSS ved at lære, hvordan du laver dit helt eget personlige fødselsdagskort.
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Tillykke Med Fødselsdagen
  - 
    title: What you will need
  - 
    title: What is HTML?
  - 
    title: 'Challenge: add another paragraph'
  - 
    title: What is CSS?
  - 
    title: 'Challenge: add more styles'
  - 
    title: Making a birthday card
  - 
    title: 'Challenge: create a personalised card'
