---
hero_image: images/happy-birthday.png
theme: tirkizna
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Sretan rođendan
description: U ovom projektu upoznat ćemo se s HTML-om i CSS-om tako što ćemo izraditi rođendansku čestitku.
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: umjetnost
technologies: html-css-javascript
site_areas: projekti
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Ono što će vam trebati
  - 
    title: Što je HTML?
  - 
    title: 'Izazov: dodajte još jedan odlomak'
  - 
    title: Što je CSS?
  - 
    title: 'Izazov: Dodavanje više stilova'
  - 
    title: Izrada rođendanske čestitke
  - 
    title: 'Izazov: izradite personaliziranu karticu'
