---
hero_image: images/banner.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Feliz Cumpleaños
description: Aprende a crear una tarjeta de cumpleaños online personalizada
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: '¿Qué es HTML?'
  - 
    title: 'Desafío: añadir otro párrafo'
  - 
    title: '¿Qué es CSS?'
  - 
    title: 'Desafío: añadir más estilos'
  - 
    title: 'Reto: Crea una tarjeta de cumpleaños'
  - 
    title: 'Desafío: crea una tarjeta personalizada'
