---
hero_image: images/banner.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Feliz Cumpleaños
description: Aprende a crear una tarjeta de cumpleaños personalizada.
original_url: https://projects.raspberrypi.org/en/projects/happy-birthday
interests: art and design
technologies: html/css
site_areas: codeclub, webdev
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: '¿Qué es HTML?'
  - 
    title: 'Reto: Añade otro párrafo'
  - 
    title: '¿Qué es CSS?'
  - 
    title: 'Reto: Añade más estilo'
  - 
    title: Crear una tarjeta de cumpleaños
  - 
    title: 'Reto: Crea una tarjeta personalizada'
  - 
    title: 'Desafío: crea una tarjeta personalizada'
