---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: La mulți ani
description: Creează o felicitare aniversară pe o pagină web
original_url: https://codeclubprojects.org/ro-RO/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: De ce vei avea nevoie
  - 
    title: Ce este HTML?
  - 
    title: 'Provocare: adaugă alt paragraf'
  - 
    title: Ce este CSS?
  - 
    title: 'Provocare: adaugă mai multe stickere'
  - 
    title: Crearea unei felicitări aniversare
  - 
    title: 'Provocare: creează o felicitare personalizată'
