---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: سالگرہ مبارک
description: ویب پیج پر سالگرہ کا ایک آن لائن کارڈ بنائیں
original_url: "https://codeclubprojects.org/en-GB/webdev/happy-birthday\n"
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: تعارف
  - 
    title: آپ کو کس چیز کی ضرورت ہو گی؟
  - 
    title: "HTML کیا ہے؟\n"
  - 
    title: 'چیلنج: دوسرا پیراگراف لکھیں'
  - 
    title: "CSS کیا ہے؟\n"
  - 
    title: 'چیلنج: مزید سٹائل شامل کریں'
  - 
    title: سالگرہ کا کارڈ بنانا
  - 
    title: 'چیلنج: ایک ذاتی کارڈ بنائیں'
