---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: ಜನ್ಮದಿನದ ಶುಭಾಶಯಗಳು
description: ವೆಬ್‌ಪುಟದಲ್ಲಿ ಆನ್‌ಲೈನ್ ಮುಖಾಂತರ ಹುಟ್ಟುಹಬ್ಬದ ಕಾರ್ಡ್ ತಯಾರಿಸಿ
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: ಪರಿಚಯ
  - 
    title: ನಿಮಗೆ ಬೇಕಾದುದು
  - 
    title: HTML ಎಂದರೇನು?
  - 
    title: 'Challenge: add another paragraph'
  - 
    title: What is CSS?
  - 
    title: 'Challenge: add more styles'
  - 
    title: Making a birthday card
  - 
    title: 'Challenge: create a personalised card'
