---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Feliz cumpleaños
description: Crea una tarjeta de cumpleaños en línea en una página web
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
- title: Introducción
- title: Lo que necesitarás
  completion: engaged
- title: "¿Qué es HTML?"
- title: 'Desafío: añade otro párrafo'
- title: "¿Qué es CSS?"
- title: 'Desafío: añade más estilos'
- title: Crear una tarjeta de cumpleaños
  completion: internal
- title: 'Desafío: crea una tarjeta personalizada'
