---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Życzenia urodzinowe
description: Naucz się, jak stworzyć własną kartkę urodzinową przy pomocy HTML i CSS.
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Co będzie potrzebne
  - 
    title: Co to jest HTML?
  - 
    title: 'Wyzwanie: dodaj kolejny akapit'
  - 
    title: Co to jest CSS?
  - 
    title: 'Wyzwanie: dodaj więcej stylów'
  - 
    title: Tworzenie kartki urodzinowej
  - 
    title: 'Wyzwanie: utwórz spersonalizowaną kartkę'
