---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Všetko najlepšie k narodeninám
description: Vytvor si online pozdrav k narodeninám na webovej stránke
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - title: Úvod
  - title: Čo budeš potrebovať
  - title: Čo je HTML?
  - title: 'Výzva: pridaj ďalší odsek'
  - title: Čo je CSS?
  - title: 'Výzva: pridaj ďalšie štýly'
  - title: Tvorba narodeninového pozdravu
  - title: 'Výzva: vytvor pozdrav podľa tvojich vlastných predstáv'
