---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Joyeux Anniversaire
description: Créer une carte d'anniversaire en ligne sur une page web
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projets
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - title: Introduction
  - title: Ce dont tu auras besoin
  - title: Qu'est-ce que le HTML ?
  - title: 'Défi: Ajouter un autre paragraphe'
  - title: Qu'est-ce que le CSS ?
  - title: 'Défi: Ajouter plus de styles'
  - title: Faire une carte d'anniversaire
  - title: 'Défi: Créer une carte personnalisée'