---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Buon compleanno
description: Crea un biglietto d'auguri online su una pagina web
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - title: Introduzione
  - title: Di cosa avrai bisogno
  - title: Cos'è l'HTML?
  - title: 'Sfida: aggiungi un altro paragrafo'
  - title: Cos'è il CSS?
  - title: 'Sfida: aggiungi più stili'
  - title: Creare un biglietto d'auguri
  - title: 'Sfida: crea una cartolina personalizzata'
