---
hero_image: images/banner.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Buon compleanno
description: Scopri come realizzare un biglietto di auguri personalizzato.
original_url: https://projects.raspberrypi.org/en/projects/happy-birthday
interests: art and design
technologies: html/css
site_areas: codeclub, webdev
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Cos'è l'HTML?
  - 
    title: 'Sfida: Aggiungi un altro paragrafo'
  - 
    title: Cos'è il CSS?
  - 
    title: 'Sfida: Aggiungi più stile'
  - 
    title: Creazione di un biglietto di auguri
  - 
    title: 'Sfida: Crea un biglietto personalizzato'
  - 
    title: 'Challenge: create a personalised card'
