---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Doğum günün kutlu olsun
description: Bir web sitesinde çevrimiçi doğum günü kartı hazırlayın
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
- title: Giriş
- title: Nelere ihtiyacınız olacak
  completion: engaged
- title: HTML nedir?
- title: 'Meydan Okuma: başka bir paragraf ekleyin'
- title: CSS nedir?
- title: 'Meydan okuma: daha fazla stil ekleyin'
- title: Doğum günü kartı yapmak
  completion: internal
- title: 'Meydan Okuma: Kişiselleştirilmiş bir kart oluşturun'
