---
hero_image: images/happy-birthday.png
theme: turkuaz
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-1, programlama-0, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: Doğum günün kutlu olsun
description: Bir web sitesinde çevrimiçi doğum günü kartı hazırlayın
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: Sanat
technologies: html-css-javascript
site_areas: projeler
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017/01/01
steps:
  - 
    title: Giriş
  - 
    title: Nelere ihtiyacınız olacak
  - 
    title: HTML nedir?
  - 
    title: 'Meydan Okuma: başka bir paragraf ekleyin'
  - 
    title: CSS nedir?
  - 
    title: 'Meydan okuma: daha fazla stil ekleyin'
  - 
    title: Doğum günü kartı yapmak
  - 
    title: 'Meydan Okuma: Kişiselleştirilmiş bir kart oluşturun'
